### PR TITLE
REFAPP-83 - Use client credentials from app config

### PR DESCRIPTION
**Pull request by ezodude**
This removes the use of
* `ASPSP_AUTH_SERVER_CLIENT_ID`
* `ASPSP_AUTH_SERVER_CLIENT_SECRET`

We rely on Authorisation Server `clientCredentials` config stored in MongoDB. See [REFAPP-44](https://openbanking.atlassian.net/browse/REFAPP-44) for more info on `clientCredentials`.

### CODE REVIEW

**Comment by ezodude** [comment]
@robmckinnon Agreed!

**Comment by robmckinnon** [comment]
@ezodude Suggest we check client e2e tests run locally against mock server configuration before merging.

**Comment by ezodude** [comment]
@robmckinnon And ... fix all the conflicts :)

**Comment by ezodude** [comment]
@splig @robmckinnon still working on getting all `e2e` tests to work :).

**Comment by ezodude** [comment]
Managed to update all ENVs - `e2e` now passing ✅ 
```
Starting selenium server... started - PID:  5155

Feature: Select ASPSP from list in order to add accounts

  Scenario: Select from list of ASPSPs in order to add accounts
    Given I am logged in
    Then I see ASPSP selection page
    When I select an ASPSP
    Then I see Accounts page

Feature: Login to see accounts

  Scenario: Logging in and out
    Given I am not logged in
    When I open homepage
    Then I see Login page
    When I login
    And I select an ASPSP
    Then I see Redirection page
    When I wait some time
    Then I see Accounts page
    And I see Account balance
    When I logout
    Then I see Login page
    When I visit accounts path
    Then I see Login page

  Scenario: Redirected to login when not logged in
    Given I am not logged in
    When I visit accounts path
    Then I see Login page

  Scenario: Logging in and server returns 500 error
    Given I am not logged in
    And I open homepage
    When I login and server returns 500 error
    Then I see Login page
    And I see login server error message

  Scenario: Logging in with invalid credentials
    Given I am not logged in
    And I open homepage
    When I login with invalid credentials
    Then I see Login page
    And I see login failure message

  Scenario: Logging in and redirect to aspsp selection page if aspsp not selected on accounts page
    Given I am not logged in
    When I open homepage
    Then I see Login page
    When I login
    And I select an ASPSP
    Then I see Redirection page
    When I wait some time
    Then I see Accounts page
    And I see Account balance
    When System removes selected aspsp from LocalStore
    And I reload page
    Then I see ASPSP selection page
    When I logout
    Then I see Login page
    When I visit accounts path
    Then I see Login page

  Scenario: Logging in and redirect to aspsp selection page if aspsp not selected on redirection page
    Given I am not logged in
    When I open homepage
    Then I see Login page
    When I login
    And I select an ASPSP
    Then I see Redirection page
    When System removes selected aspsp from LocalStore
    And I reload page
    Then I see ASPSP selection page
    When I logout
    Then I see Login page
    When I visit accounts path
    Then I see Login page

7 scenarios (7 passed)
59 steps (59 passed)
0m25.189s
```

**Pull request merged**
