### PR TITLE
Ref #REFAPP-112 Allow Multiple Sessions

### PR DESCRIPTION
**Pull request by splig**
Also
- Remove unused `session/check` route, and remove `session.check` function.
- Remove unneeded `AUTHORIZATION` env var.
- Rename `getAuthFromSession` function to `validSession`, returns `true` when session exists, otherwise `false`.
- Use `validSession` to check authorization header represents valid session id.

### CODE REVIEW

**Comment by robmckinnon** [comment]
I'll add unit tests.

**Comment by robmckinnon** [comment]
Tested locally, e2e tests run successfully. Successfully manually tested two concurrent open sessions in different browsers.

**Comment by ezodude** [comment]
Nice one.

**Comment by BillForster** [comment]
Also tested with 3 concurrently.

**Pull request merged**
