### PR TITLE
REFAPP-3 Enable Mutual TLS (MATLS) to be used to all connections to external servers

### PR DESCRIPTION
**Pull request by daniel-kuras**
- Create client key, client certificate, certification authority (CA) certificate for local environment (reference application ecosystem); client certificate is signed using above CA certificate
- Define client/ca certificates and client key as environment variables (encoded using base64)
- Upgraded all REST clients/agents to use superagent
- Create wrapper method over superagent to add all required keys and certificates for MATLS connections
- Updated proxy connector to WriteRead API to use MATLS
- Use client key to sign jwt token
- disable domain verification on MATLS connection (TLS_REJECT_UNAUTHORIZED)

Documentation:

# Security certificates in Reference App ecosystem

OpenBanking specification requires all parties to use Mutual TLS for every connection. OpenBanking uses its own Certification Authority certificate (created from OpenBanking Root certificate) to sign clients (TPP) and servers (ASPSP) certificates.
- For ASPSP server certificate in pair with certificate key and CA certificate must be used to secure resources provided by servers.
- For TPP client certificate in pair with certificate key and CA certificate must be used to establish secured connection with servers (ASPSP Authorization/Resource Server, OpenBanking Directory and OpenId Configuration).

For the purpose of Reference App "dummy" CA certificate (for simplicity application does not use any root certificate to sign CA cert), Mock server certificate and TPP Reference Server certificate have been created. Also, Mock server certificate and TPP Reference Server certificate have been signed by "dummy" CA certificate.
The created certificates allow running MATLS secured Reference App ecosystem on local environment or any hosted version.
In case someone would like to create its own certificates the receipt below explains how this can be done. Bear in mind that TPP Server and Mock Server accepts certificates and key as global variable encoded using base64. 

**How to create own certificates.**

- Create the CA Key and Certificate for signing Client/Server Certs
openssl genrsa -des3 -out ca.key 4096
openssl req -new -x509 -days 730 -key ca.key -out ca.crt

- Create the Server Key, CSR, and Certificate
openssl genrsa -des3 -out server.key 1024
openssl req -new -key server.key -out server.csr

- Remove passphrase from client key
chmod 0600 server.key
ssh-keygen -p -P [PASSPHRASE_FOR_SERVER_CERT] -N ""  -f ./server.key

- Self signing server csr using CA cert and generate server certificate
openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt

- Create the Client Key and CSR
openssl genrsa -des3 -out client.key 1024
openssl req -new -key client.key -out client.csr

- Remove passphrase from client key
chmod 0600 client.key
ssh-keygen -p -P [PASSPHRASE_FOR_CLIENT_CERT] -N ""  -f ./client.key

- Self signing client csr using CA cert and generate server certificate
openssl x509 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt

### CODE REVIEW

**Comment by ezodude** [comment]
@daniel-kuras I’d like to understand where `CA_CERT`, `CLIENT_CERT` & `CLIENT_KEY` will come from?

**Comment by ezodude** [comment]
@daniel-kuras thanks for the clarification. 👍 

I can see how this will work locally - do you need to update ENVs on heroku?

Also, for completeness we should probably update the `.env.sample` file.

**Comment by ezodude** [comment]
Happy for this to be merged.

**Comment by daniel-kuras** [comment]
@ezodude 
On heroku there are 2 options
1. Only ref app + mock server, new global vars from .env file should be added via console and url to mock server should be updated https and 443
2. ref app + ozone (no ref mock server) CA/CLIENT_CERT, CLIENT_KEY provided by OBD have to be set up on heroku console

**Comment by ezodude** [comment]
@daniel-kuras sounds good. For now, option 1?

**Comment by daniel-kuras** [comment]
guys, there is a problem with heroku. Earlier I found out that MATLS won't work then Freddi mixed up my head that we don’t need a server but only client… I’ve just realized that it is true only if we want to integrate with Ozone. Unfortunately, our mock server won't work as heroku proxy use it’s own cert, does not allow for MATLS and offload TLS before traffic is sent to the server (I think) :confused:. My PRs are good to go but they will break heroku deployment so I am not merging it. You will need to check it and come with other solution to run fully mocked reference app ecosystem in the cloud. I’ve added all required environment variables (apart from updating link to mock server on tpp server) to both heroku projects. Sorry for leaving it with you…

**Comment by ezodude** [comment]
@splig @daniel-kuras @robmckinnon After more discussions, I've 
* Introduced a `MTLS_ENABLED` flag.
* Corrected and clarified the mapping of certs with expected OB Directory integration.
* Updated README to slightly clarify explanation of MTLS.

**Comment by ezodude** [comment]
@robmckinnon Great updates. Should we merge?

**Pull request merged**
